#!/usr/bin/env zsh

xenv() {
    local source_files_dir="$(mktemp -d)"

    python "$XENV_HOME/xenv.py" --source-files-dir "$source_files_dir" "$@"

    local retcode=$?

    for file in $(find "$source_files_dir" -maxdepth 1 -type f); do
       source "$file"
    done

    rm -rf "$source_files_dir" 2> /dev/null

    return $retcode
}

export XENV_HOME="$HOME/.config/xenv"

