#!/usr/bin/env zsh

export XENV_DBG=1

rename_function() {
    local function_name="$1"
    local new_function_name="$2"

    # cmfh = command_not_found_handler
    local initial_function="$(which "$function_name")"

    if [[ $? -eq 0 ]]; then
        local function_lines="$(echo "$initial_function" | wc -l)"

        local new_function="$(echo -n "${new_function_name}() \{"; cat "$initial_function" | tail -n $((function_lines - 1)))"

        eval "$new_function"
    else
        return 1
    fi
}

xenv() {
    export XENV_EXPORT_SCRIPT=$("mktemp")

    python -m xenv "$@"

    local retcode=$?

    if [[ -f "$XENV_EXPORT_SCRIPT" ]]
    then
        source "$XENV_EXPORT_SCRIPT"

        [[ -z "$XENV_DBG" ]] && { rm "$XENV_EXPORT_SCRIPT"; echo "Arquivo removido"; }
    fi

    unset XENV_EXPORT_SCRIPT

    return $retcode
}

[ -z "$XENV_HOME" ] && export XENV_HOME="${XDG_CONFIG_HOME:-$HOME/.config}"/xenv

